name: Release Windows GUI

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DENABLE_GUI=ON

    - name: Build
      run: |
        cd build
        ninja

    - name: Bundle Qt Dependencies
      run: |
        windeployqt build/bin/LightwatchAI.exe

    - name: Test Binaries
      run: |
        cd build/bin
        ./LightwatchAI.exe --version
        ./lightwatch_cli.exe --help

    - name: Package
      run: |
        cd build/bin
        7z a ../../LightwatchAI.zip LightwatchAI.exe *

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: LightwatchAI v${{ github.run_number }}
        tag_name: v${{ github.run_number }}
        body: |
          Automated release of LightwatchAI GUI for Windows.
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LightwatchAI.zip
        asset_name: LightwatchAI.zip
        asset_content_type: application/zip
