name: LightwatchAI Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DENABLE_GUI=ON
      - name: Build binaries
        run: |
          cd build
          cmake --build . --config Release
      - name: Validate executables
        shell: cmd
        run: |
          cd build\bin
          if not exist lightwatch_gui.exe exit 1
          if not exist lightwatch_cli.exe exit 1
          if not exist dummy_checkpoint.bin fsutil file createnew dummy_checkpoint.bin 3412992
          lightwatch_cli.exe dummy_checkpoint.bin --len 1 || exit /b 0
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: LightwatchAI v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: Automated release of LightwatchAI GUI for Windows.
          files: |
            build/bin/lightwatch_gui.exe
            build/bin/lightwatch_cli.exe
            build/bin/lightwatch_run.exe
            build/bin/lightwatch_train.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
