name: Release Windows GUI

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        install-deps: 'true'

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DENABLE_GUI=ON

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Bundle Qt Dependencies
      run: |
        windeployqt build/bin/lightwatch_gui.exe

    - name: Test Binaries
      run: |
        cd build/bin
        ./lightwatch_train.exe --help
        ./lightwatch_run.exe --help
        ./data_preprocess.exe --help
        ./simple_cuda_test.exe
        if exist lightwatch_gui.exe (echo GUI exe exists) else (exit 1)

    - name: Package
      run: |
        cd build/bin
        7z a ../../lightwatch_gui.zip *

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: lightwatch_gui.zip
        body: |
          Automated release of LightwatchAI GUI for Windows.
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ github.token }}
